import { fetchTranscriptViaApi, fetchVideoMetadata, fetchWithTimeout, pickCaptionTrack, TranscriptItem } from "@/lib/youtube";
import { secondsToTimestamp } from "@/lib/time";

function decodeHtml(text: string) {
  return String(text || "")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&#(\d+);/g, (_, code) => String.fromCharCode(Number(code)));
}

function stripTags(text: string) {
  return decodeHtml(String(text || "").replace(/<[^>]+>/g, ""));
}

export function parseTranscriptXml(xml: string): TranscriptItem[] {
  const items: TranscriptItem[] = [];
  const regex = /<text\b([^>]*)>([\s\S]*?)<\/text>/g;
  let match;

  while ((match = regex.exec(xml))) {
    const attrText = match[1];
    const body = stripTags(match[2]).replace(/\s+/g, " ").trim();
    if (!body) continue;

    const start = Number((attrText.match(/\bstart="([^"]+)"/) || [])[1] || 0);
    const duration = Number((attrText.match(/\bdur="([^"]+)"/) || [])[1] || 0);
    items.push({ start, duration, end: start + duration, text: body });
  }

  return items;
}

export function parseTranscriptJson3(payload: string): TranscriptItem[] {
  const data = JSON.parse(payload);
  const events = Array.isArray(data?.events) ? data.events : [];

  return events
    .map((event: any) => {
      const segments = Array.isArray(event.segs) ? event.segs : [];
      const text = segments
        .map((segment: any) => segment.utf8 || "")
        .join("")
        .replace(/\s+/g, " ")
        .trim();

      if (!text) return null;
      const start = Number(event.tStartMs || 0) / 1000;
      const duration = Number(event.dDurationMs || 0) / 1000;
      return { start, duration, end: start + duration, text };
    })
    .filter((item: TranscriptItem | null): item is TranscriptItem => Boolean(item));
}

async function fetchTranscriptViaPackage(videoId: string, language: string): Promise<TranscriptItem[]> {
  const { YoutubeTranscript } = await import("youtube-transcript");
  const rows = await YoutubeTranscript.fetchTranscript(videoId, { lang: language });

  return rows
    .map((row: any) => {
      const start = Number(row.offset || 0) / 1000;
      const duration = Number(row.duration || 0) / 1000;
      const text = String(row.text || "").replace(/\s+/g, " ").trim();
      if (!text) return null;
      return { start, duration, end: start + duration, text };
    })
    .filter((item: TranscriptItem | null): item is TranscriptItem => Boolean(item));
}

export function transcriptToText(items: TranscriptItem[]) {
  return items.map((item) => `[${secondsToTimestamp(item.start)} - ${secondsToTimestamp(item.end)}] ${item.text}`).join("\n");
}

export async function getTranscript({ videoId, language }: { videoId: string; language: string }) {
  if (!["id", "en"].includes(language)) throw new Error("Pilihan bahasa tidak valid.");

  const metadata = await fetchVideoMetadata(videoId);
  if (!metadata.captions.length) throw new Error("Video ini tidak memiliki subtitle yang bisa diambil.");

  const track = pickCaptionTrack(metadata.captions, language);
  if (!track) {
    const available = metadata.captions
      .map((caption) => `${caption.languageCode}${caption.name?.simpleText ? ` (${caption.name.simpleText})` : ""}`)
      .join(", ");
    throw new Error(`Subtitle bahasa ${language === "id" ? "Indonesia" : "English"} tidak tersedia. Bahasa tersedia: ${available || "tidak diketahui"}.`);
  }

  const transcriptUrl = new URL(track.baseUrl);
  transcriptUrl.searchParams.set("fmt", "json3");

  const response = await fetchWithTimeout(transcriptUrl.toString(), {
    headers: {
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/124 Safari/537.36",
    },
  });

  if (!response.ok) throw new Error(`Gagal mengambil subtitle. Status ${response.status}.`);

  const body = await response.text();
  let items: TranscriptItem[] = [];
  try {
    items = parseTranscriptJson3(body);
  } catch {
    items = parseTranscriptXml(body);
  }

  if (!items.length) {
    try {
      items = await fetchTranscriptViaPackage(videoId, track.languageCode || language);
    } catch {
      items = await fetchTranscriptViaApi(videoId, track.languageCode || language, metadata.visitorData);
    }
  }

  if (!items.length) throw new Error("Subtitle ditemukan, tetapi isinya kosong atau tidak bisa diproses.");

  return {
    videoId,
    title: metadata.title,
    languageCode: track.languageCode,
    languageName: track.nameText || track.languageCode,
    isAutoGenerated: track.kind === "asr",
    itemCount: items.length,
    items,
    text: transcriptToText(items),
  };
}
